seed = 317

# data prep settings
use_gaussian = true
gaussian_iou = 0.7
down_ratio = 4
max_objs = 128
num_classes = 80
num_dets = 1000
test_scales = [1.0]
topk_k = 70
nms_threshold = 0.5
ae_threshold = 0.5
val_cache_rate = 1.0
nms_gaussian_w_exp = 8

# training settings
precision = "32-true"
train_patch_size = [511, 511]
batch_size = 48
max_steps = 480000
lr = 0.00025
lr_step_size = 450000
lr_gamma = 0.1
val_frequency = 5
logging_frequency = 100
ckpt_frequency = 5
gamma = 0.1

# Model settings
n = 5
nstack = 2
conv_dim = 256
dims = [256, 256, 384, 384, 384, 512]
num_modules = [2, 2, 2, 2, 2, 4]
deep_supervision = true